### ISSUE TITLE
ImportError: No module named writer

### ISSUE THREAD

**Issue by hamidpalangi** [ruotianluo/NeuralDialog-CVAE-pytorch#1]
Hi,

Thanks for great work. Trying to run the codes but get the following error:
```
File "~/NeuralDialog-CVAE-pytorch/models/cvae.py", line 26, in <module>
import tensorboard.writer
ImportError: No module named writer
```

Using TF 1.3 and Torch 0.3, below is a snapshot of part of `pip freeze`:

![capture](https://user-images.githubusercontent.com/13631873/40631067-86ad5542-628d-11e8-850d-6387f5ab8483.PNG)

Can you please help?

Thanks!
Hamid

**Comment by ruotianluo** [comment]
replace all tensorboard with tensorboardX

**Comment by hamidpalangi** [comment]
Thanks, it resolved. 

Now getting: `RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7005 but linked against 6021`. Checked out my `LD_LIBRARY_PATH` which is `/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64`. Inside `/usr/local/cuda/lib64` folder their is no `libcudnn.so.7.0.05`. Weird because didn't have this issue running PyTorch for another project. Any ideas?

Thanks!
Hamid

**Comment by ruotianluo** [comment]
What's your version of pytorch.

**Comment by hamidpalangi** [comment]
0.3

**Comment by ruotianluo** [comment]
pytorch 0.3 does use cudnn7.

**Comment by hamidpalangi** [comment]
Closing this one, started using pytorch 0.4.
