### ISSUE TITLE
Assertion Error after few iterations

### ISSUE THREAD

**Issue by siddsax** [ruotianluo/NeuralDialog-CVAE-pytorch#2]
Hi

I have been trying to run the code, but after a few iterations ( sometimes after a couple iterations, sometimes after a lot more), I get assertion error here 
https://github.com/ruotianluo/NeuralDialog-CVAE-pytorch/blob/master/models/cvae.py#L273

Any idea why this might be happening, I am using the default settings with tensorboardX.

Thanks!

**Comment by ruotianluo** [comment]
This assertion is trying to make sure that padding_idx(which is 0) has 0 zero embedding, and all the other have at least one non-zero dimension in its embedding.

Try to look at the output of the assersion.

(In principle, the assersion shouldn't fail. Wierd.)

**Comment by ruotianluo** [comment]
This didn't happen to me. Try with the master. (It now uses pytorch 0.4)

**Comment by siddsax** [comment]
Thanks a lot for the update. I'll check if it works for me now.
