### ISSUE TITLE
IllegalFlagValueError: flag --equal_batch=True: flag value must be a string

### ISSUE THREAD

**Issue by hamidpalangi** [ruotianluo/NeuralDialog-CVAE-pytorch#3]
Getting the following error now, any idea?

Thanks!
Hamid

![capture](https://user-images.githubusercontent.com/13631873/40992410-95daccb0-68ab-11e8-9603-3a6267b20a9e.PNG)

**Comment by hamidpalangi** [comment]
The current packages etc: 
![capture](https://user-images.githubusercontent.com/13631873/40992630-31cdcf1e-68ac-11e8-9ad1-00fcfc455d64.PNG)

**Comment by ruotianluo** [comment]
Try replace with DEFINE_boolean? I never use tensorflow flags in my own project. This looks like a bug that has been fixed in newer tensorflow. (I used tf1.5)

**Comment by hamidpalangi** [comment]
Resolved, thanks. 

Question: Were you able to re-generate their results? E.g., match their reported BLEU scores?

**Comment by ruotianluo** [comment]
I forgot. I checked the training curve with original tensorflow code. The training curve is not exactly the same, but very close.
